- +experiment=vl4str
- model=vl4str
- dataset=real
- data.root_dir=/home/aitrain/Documents/Krisztian/CLIP4STR/dataset/
- trainer.max_epochs=150
- trainer.gpus=2
- trainer.accumulate_grad_batches=1
- model.lr=2e-5
- model.weight_decay=0.01
- model.batch_size=64
- model.image_freeze_nlayer=0
- model.text_freeze_nlayer=0
- model.image_detach=false
- model.context_length=4
- model.max_label_length=2
- model.clip_pretrained=/home/aitrain/Documents/Krisztian/CLIP4STR/pretrained/clip/ViT-B-16.pt
- ++trainer.check_val_every_n_epoch=1
- ++trainer.log_every_n_steps=10
- ++trainer.num_sanity_val_steps=0
