hydra:
  run:
    dir: /home/aitrain/Documents/Krisztian/CLIP4STR/code/CLIP4STR
  sweep:
    dir: ${abs_root}/output/${model.name}_${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: config
  overrides:
    hydra:
    - hydra.run.dir="/home/aitrain/Documents/Krisztian/CLIP4STR/code/CLIP4STR"
    - hydra.job.name=train_ddp_process_1
    - hydra.mode=RUN
    task:
    - +experiment=vl4str
    - model=vl4str
    - dataset=real
    - data.root_dir=/home/aitrain/Documents/Krisztian/CLIP4STR/dataset/
    - trainer.max_epochs=150
    - trainer.gpus=2
    - trainer.accumulate_grad_batches=1
    - model.lr=2e-5
    - model.weight_decay=0.01
    - model.batch_size=64
    - model.image_freeze_nlayer=0
    - model.text_freeze_nlayer=0
    - model.image_detach=false
    - model.context_length=4
    - model.max_label_length=2
    - model.clip_pretrained=/home/aitrain/Documents/Krisztian/CLIP4STR/pretrained/clip/ViT-B-16.pt
    - ++trainer.check_val_every_n_epoch=1
    - ++trainer.log_every_n_steps=10
    - ++trainer.num_sanity_val_steps=0
  job:
    name: train_ddp_process_1
    chdir: null
    override_dirname: ++trainer.check_val_every_n_epoch=1,++trainer.log_every_n_steps=10,++trainer.num_sanity_val_steps=0,+experiment=vl4str,data.root_dir=/home/aitrain/Documents/Krisztian/CLIP4STR/dataset/,dataset=real,model.batch_size=64,model.clip_pretrained=/home/aitrain/Documents/Krisztian/CLIP4STR/pretrained/clip/ViT-B-16.pt,model.context_length=4,model.image_detach=false,model.image_freeze_nlayer=0,model.lr=2e-5,model.max_label_length=2,model.text_freeze_nlayer=0,model.weight_decay=0.01,model=vl4str,trainer.accumulate_grad_batches=1,trainer.gpus=2,trainer.max_epochs=150
    id: ???
    num: ???
    config_name: main
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /home/aitrain/Documents/Krisztian/CLIP4STR/code/CLIP4STR
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/aitrain/Documents/Krisztian/CLIP4STR/code/CLIP4STR/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: /home/aitrain/Documents/Krisztian/CLIP4STR/code/CLIP4STR
    choices:
      experiment: vl4str
      dataset: real
      charset: 10_numbers
      model: vl4str
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
